# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1d2-uNoWqxJM0_fAOa8pZMZbdpaYzQ4cd

Given a time in -hour AM/PM format, convert it to military (24-hour) time.

Note: - 12:00:00AM on a 12-hour clock is 00:00:00 on a 24-hour clock.
- 12:00:00PM on a 12-hour clock is 12:00:00 on a 24-hour clock.

Example
*  s= '12:01:00PM'
      Return '12:01:00'.

*  s= '12:01:00AM'
      Return '00:01:00'.
"""

def timeConversion(s):
    period = s[-2:]

    # Extract hours, minutes, and seconds as strings
    hh_str = s[:2]
    mm = s[3:5]
    ss = s[6:8]

    # Convert hours from string to integer
    hh = int(hh_str)

    # Convert hours to 24-hour format
    if period == "AM":
        if hh == 12:  # Midnight case
            hh = 0
    else:  # PM case
        if hh != 12:  # Noon case should stay as 12
            hh += 12

    # Format the hours to be two digits without using built-in functions
    hh_24 = f"{hh:02}"

    # Construct the 24-hour format time string
    return f"{hh_24}:{mm}:{ss}"

timeConversion('01:00:01AM')

